name = "your-orders-api"
main = "backend/src/worker.js"
compatibility_date = "2024-01-15"

[[d1_databases]]
binding = "DB"
database_name = "your-orders-database"
database_id = "1e5586ee-a77a-4e91-b33a-9e4e1977c0f1"

# Production environment (default)
[vars]
API_KEY = "2c996b8297d684972e130ec768feafdba9de1c62f77cd4fcfbb8db35d2f070b5"
TELEGRAM_BOT_TOKEN = "7539435931:AAHmLXhTIGtSen4YPOzQCsp-3STqOmFss9c"
TELEGRAM_CHAT_ID = "6772928207"
ENVIRONMENT = "production"
CORS_ORIGIN = "https://your-pages-domain.pages.dev"

# Development environment
[env.development]
[[env.development.d1_databases]]
binding = "DB"
database_name = "your-orders-database"
database_id = "1e5586ee-a77a-4e91-b33a-9e4e1977c0f1"

[env.development.vars]
API_KEY = "2c996b8297d684972e130ec768feafdba9de1c62f77cd4fcfbb8db35d2f070b5"
TELEGRAM_BOT_TOKEN = "7539435931:AAHmLXhTIGtSen4YPOzQCsp-3STqOmFss9c"
TELEGRAM_CHAT_ID = "6772928207"
ENVIRONMENT = "development"
CORS_ORIGIN = "http://localhost:4173"